version: '3.8'
services:
  mytodolistapp:
    build: .
    ports:
      - 6789:8881
    environment:
      - HOST=0.0.0.0
      - MONGODB_URL=mongodb://mongoTodoListdb:27017/
    depends_on:
      - mongoTodoListdb

  mongoTodoListdb:
    restart: always
    image: mongo:6-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
    ports:
      - '27017:27017'
    volumes:
      - mongo-todo-list-data:/data/db
volumes:
  mongo-todo-list-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/mfv-hn-computer-0015/docker/local_mount/mongo-todo-list-data