version: '3.8'
services:
  mytodolistapp:
    build: .
    ports:
      - 6789:8881
    environment:
      - HOST=0.0.0.0
      - MONGODB_URL=mongodb://mongoTodoListdb:27017/
    depends_on:
      - mongoTodoListdb

  mongoTodoListdb:
    restart: always
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6: