# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"


  build-push-docker-image:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
          docker_layer_caching: true
      - run:
          name: "show docker info"
          command: |
            echo "branch name: " $CIRCLE_BRANCH ", hash: "$CIRCLE_SHA1
            echo $DOCKER_PWD
            echo $DOCKER_USER_NAME

      - run:
          name: "Build docker"
          command: docker build -t hbc08/bch:$CIRCLE_SHA1 .
      - run:
          name: "push docker"
          command: |
            echo "$DOCKER_PWD" | docker login -u "$DOCKER_USER_NAME" --password-stdin
            docker push hbc08/bch:$CIRCLE_SHA1


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  push-image-workflow:
    jobs:
      - build-push-docker-image
